//! MF-parity gold corpus replay: `variant-allocator-corpus/cases.json`.
//!
//! Every case was generated by driving the real
//! `Microsoft.FeatureManagement.FeatureManager.GetVariantAsync` (pinned to
//! 4.7.0); see `variant-allocator-corpus/README.md`. This SDK's
//! `assign_variant` must match every case bit-for-bit.

use serde::Deserialize;
use std::fs;
use std::path::PathBuf;
use toggly::definitions::{Allocation, FeatureDefinition, FeatureFilter, RequirementType, Variant};
use toggly::eval::{assign_variant, Engine};
use toggly::EvalContext;

const EXPECTED_CASE_COUNT: usize = 18;

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct Case {
    id: String,
    feature: CaseFeature,
    targeting: CaseTargeting,
    expected: CaseExpected,
    #[serde(default)]
    ignore_case: bool,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct CaseFeature {
    name: String,
    #[serde(default)]
    enabled_for: Vec<CaseFilter>,
    #[serde(default)]
    variants: Vec<Variant>,
    #[serde(default)]
    allocation: Option<Allocation>,
}

#[derive(Debug, Deserialize)]
struct CaseFilter {
    name: String,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct CaseTargeting {
    user_id: Option<String>,
    #[serde(default)]
    groups: Vec<String>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct CaseExpected {
    variant_name: Option<String>,
    configuration_value: Option<serde_json::Value>,
    enabled: bool,
    assignment_reason: String,
}

fn resolve_corpus_path() -> Option<PathBuf> {
    let cwd = std::env::current_dir().ok()?;
    let mut walk = cwd;
    for _ in 0..6 {
        let candidate = walk.join("variant-allocator-corpus/cases.json");
        if candidate.is_file() {
            return Some(candidate);
        }
        if !walk.pop() {
            break;
        }
    }
    None
}

fn load_cases() -> Vec<Case> {
    let path = resolve_corpus_path().expect("variant-allocator-corpus/cases.json not found");
    let text = fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    serde_json::from_str(&text).unwrap_or_else(|e| panic!("parse {}: {e}", path.display()))
}

fn to_definition(case: &Case) -> FeatureDefinition {
    FeatureDefinition {
        feature_key: case.feature.name.clone(),
        filters: case
            .feature
            .enabled_for
            .iter()
            .map(|f| FeatureFilter {
                name: f.name.clone(),
                parameters: Default::default(),
            })
            .collect(),
        metrics: vec![],
        secured_feature: false,
        client_sdk_enabled: true,
        requirement_type: RequirementType::Any,
        context_kind: None,
        context_requirement_type: None,
        variants: case.feature.variants.clone(),
        allocation: case.feature.allocation.clone(),
    }
}

fn to_context(case: &Case) -> EvalContext {
    EvalContext {
        identity: case.targeting.user_id.clone(),
        groups: case.targeting.groups.clone(),
        ..EvalContext::default()
    }
}

#[test]
fn corpus_has_expected_case_count() {
    let cases = load_cases();
    assert_eq!(
        cases.len(),
        EXPECTED_CASE_COUNT,
        "unexpected corpus case count; update EXPECTED_CASE_COUNT if the corpus grew intentionally"
    );
}

#[test]
fn gold_corpus_matches_mf_bit_for_bit() {
    let engine = Engine::with_defaults();
    for case in load_cases() {
        let definition = to_definition(&case);
        let context = to_context(&case);

        let filter_enabled = engine
            .evaluate(&definition, &context)
            .unwrap_or_else(|e| panic!("case {}: filter evaluate error: {e}", case.id));

        let assignment = assign_variant(&definition, filter_enabled, &context, case.ignore_case);

        assert_eq!(
            assignment.variant_name, case.expected.variant_name,
            "case {}: variantName mismatch",
            case.id
        );
        assert_eq!(
            assignment.configuration_value, case.expected.configuration_value,
            "case {}: configurationValue mismatch",
            case.id
        );
        assert_eq!(
            assignment.enabled, case.expected.enabled,
            "case {}: enabled mismatch",
            case.id
        );
        assert_eq!(
            assignment.assignment_reason.as_str(),
            case.expected.assignment_reason,
            "case {}: assignmentReason mismatch",
            case.id
        );
    }
}
