sonar.projectKey=toggly-sdks-javascript
sonar.organization=ops-ai
sonar.sources=src
sonar.tests=tests
sonar.test.inclusions=tests/**/*.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=dist/**,node_modules/**
