// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: usage.proto

package usagepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FeatureStat struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AppKey           string                 `protobuf:"bytes,1,opt,name=appKey,proto3" json:"appKey,omitempty"`
	Environment      string                 `protobuf:"bytes,2,opt,name=environment,proto3" json:"environment,omitempty"`
	Time             *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
	Stats            []*StatMessage         `protobuf:"bytes,4,rep,name=stats,proto3" json:"stats,omitempty"`
	TotalUniqueUsers int32                  `protobuf:"varint,5,opt,name=totalUniqueUsers,proto3" json:"totalUniqueUsers,omitempty"`
	InstanceName     *string                `protobuf:"bytes,6,opt,name=instanceName,proto3,oneof" json:"instanceName,omitempty"`
	ProcessStartTime *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=processStartTime,proto3,oneof" json:"processStartTime,omitempty"`
	AppVersion       *string                `protobuf:"bytes,8,opt,name=appVersion,proto3,oneof" json:"appVersion,omitempty"`
	UniqueUserHashes []int32                `protobuf:"varint,9,rep,packed,name=uniqueUserHashes,proto3" json:"uniqueUserHashes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FeatureStat) Reset() {
	*x = FeatureStat{}
	mi := &file_usage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeatureStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureStat) ProtoMessage() {}

func (x *FeatureStat) ProtoReflect() protoreflect.Message {
	mi := &file_usage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureStat.ProtoReflect.Descriptor instead.
func (*FeatureStat) Descriptor() ([]byte, []int) {
	return file_usage_proto_rawDescGZIP(), []int{0}
}

func (x *FeatureStat) GetAppKey() string {
	if x != nil {
		return x.AppKey
	}
	return ""
}

func (x *FeatureStat) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *FeatureStat) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *FeatureStat) GetStats() []*StatMessage {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *FeatureStat) GetTotalUniqueUsers() int32 {
	if x != nil {
		return x.TotalUniqueUsers
	}
	return 0
}

func (x *FeatureStat) GetInstanceName() string {
	if x != nil && x.InstanceName != nil {
		return *x.InstanceName
	}
	return ""
}

func (x *FeatureStat) GetProcessStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ProcessStartTime
	}
	return nil
}

func (x *FeatureStat) GetAppVersion() string {
	if x != nil && x.AppVersion != nil {
		return *x.AppVersion
	}
	return ""
}

func (x *FeatureStat) GetUniqueUserHashes() []int32 {
	if x != nil {
		return x.UniqueUserHashes
	}
	return nil
}

type StatMessage struct {
	state                                protoimpl.MessageState `protogen:"open.v1"`
	Feature                              string                 `protobuf:"bytes,1,opt,name=feature,proto3" json:"feature,omitempty"`
	EnabledCount                         int32                  `protobuf:"varint,2,opt,name=enabledCount,proto3" json:"enabledCount,omitempty"`
	DisabledCount                        int32                  `protobuf:"varint,3,opt,name=disabledCount,proto3" json:"disabledCount,omitempty"`
	UniqueContextIdentifierEnabledCount  int32                  `protobuf:"varint,4,opt,name=uniqueContextIdentifierEnabledCount,proto3" json:"uniqueContextIdentifierEnabledCount,omitempty"`
	UniqueContextIdentifierDisabledCount int32                  `protobuf:"varint,5,opt,name=uniqueContextIdentifierDisabledCount,proto3" json:"uniqueContextIdentifierDisabledCount,omitempty"`
	UniqueRequestEnabledCount            int32                  `protobuf:"varint,6,opt,name=uniqueRequestEnabledCount,proto3" json:"uniqueRequestEnabledCount,omitempty"`
	UniqueRequestDisabledCount           int32                  `protobuf:"varint,7,opt,name=uniqueRequestDisabledCount,proto3" json:"uniqueRequestDisabledCount,omitempty"`
	UsedCount                            int32                  `protobuf:"varint,8,opt,name=usedCount,proto3" json:"usedCount,omitempty"`
	UniqueUsersUsedCount                 int32                  `protobuf:"varint,9,opt,name=uniqueUsersUsedCount,proto3" json:"uniqueUsersUsedCount,omitempty"`
	UniqueUserHashes                     []int32                `protobuf:"varint,10,rep,packed,name=uniqueUserHashes,proto3" json:"uniqueUserHashes,omitempty"`
	unknownFields                        protoimpl.UnknownFields
	sizeCache                            protoimpl.SizeCache
}

func (x *StatMessage) Reset() {
	*x = StatMessage{}
	mi := &file_usage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatMessage) ProtoMessage() {}

func (x *StatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_usage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatMessage.ProtoReflect.Descriptor instead.
func (*StatMessage) Descriptor() ([]byte, []int) {
	return file_usage_proto_rawDescGZIP(), []int{1}
}

func (x *StatMessage) GetFeature() string {
	if x != nil {
		return x.Feature
	}
	return ""
}

func (x *StatMessage) GetEnabledCount() int32 {
	if x != nil {
		return x.EnabledCount
	}
	return 0
}

func (x *StatMessage) GetDisabledCount() int32 {
	if x != nil {
		return x.DisabledCount
	}
	return 0
}

func (x *StatMessage) GetUniqueContextIdentifierEnabledCount() int32 {
	if x != nil {
		return x.UniqueContextIdentifierEnabledCount
	}
	return 0
}

func (x *StatMessage) GetUniqueContextIdentifierDisabledCount() int32 {
	if x != nil {
		return x.UniqueContextIdentifierDisabledCount
	}
	return 0
}

func (x *StatMessage) GetUniqueRequestEnabledCount() int32 {
	if x != nil {
		return x.UniqueRequestEnabledCount
	}
	return 0
}

func (x *StatMessage) GetUniqueRequestDisabledCount() int32 {
	if x != nil {
		return x.UniqueRequestDisabledCount
	}
	return 0
}

func (x *StatMessage) GetUsedCount() int32 {
	if x != nil {
		return x.UsedCount
	}
	return 0
}

func (x *StatMessage) GetUniqueUsersUsedCount() int32 {
	if x != nil {
		return x.UniqueUsersUsedCount
	}
	return 0
}

func (x *StatMessage) GetUniqueUserHashes() []int32 {
	if x != nil {
		return x.UniqueUserHashes
	}
	return nil
}

type StatResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeatureCount  int32                  `protobuf:"varint,1,opt,name=featureCount,proto3" json:"featureCount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatResult) Reset() {
	*x = StatResult{}
	mi := &file_usage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatResult) ProtoMessage() {}

func (x *StatResult) ProtoReflect() protoreflect.Message {
	mi := &file_usage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatResult.ProtoReflect.Descriptor instead.
func (*StatResult) Descriptor() ([]byte, []int) {
	return file_usage_proto_rawDescGZIP(), []int{2}
}

func (x *StatResult) GetFeatureCount() int32 {
	if x != nil {
		return x.FeatureCount
	}
	return 0
}

var File_usage_proto protoreflect.FileDescriptor

const file_usage_proto_rawDesc = "" +
	"\n" +
	"\vusage.proto\x12\x05Usage\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcd\x03\n" +
	"\vFeatureStat\x12\x16\n" +
	"\x06appKey\x18\x01 \x01(\tR\x06appKey\x12 \n" +
	"\venvironment\x18\x02 \x01(\tR\venvironment\x12.\n" +
	"\x04time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12(\n" +
	"\x05stats\x18\x04 \x03(\v2\x12.Usage.StatMessageR\x05stats\x12*\n" +
	"\x10totalUniqueUsers\x18\x05 \x01(\x05R\x10totalUniqueUsers\x12'\n" +
	"\finstanceName\x18\x06 \x01(\tH\x00R\finstanceName\x88\x01\x01\x12K\n" +
	"\x10processStartTime\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x01R\x10processStartTime\x88\x01\x01\x12#\n" +
	"\n" +
	"appVersion\x18\b \x01(\tH\x02R\n" +
	"appVersion\x88\x01\x01\x12.\n" +
	"\x10uniqueUserHashes\x18\t \x03(\x05B\x02\x10\x01R\x10uniqueUserHashesB\x0f\n" +
	"\r_instanceNameB\x13\n" +
	"\x11_processStartTimeB\r\n" +
	"\v_appVersion\"\x97\x04\n" +
	"\vStatMessage\x12\x18\n" +
	"\afeature\x18\x01 \x01(\tR\afeature\x12\"\n" +
	"\fenabledCount\x18\x02 \x01(\x05R\fenabledCount\x12$\n" +
	"\rdisabledCount\x18\x03 \x01(\x05R\rdisabledCount\x12P\n" +
	"#uniqueContextIdentifierEnabledCount\x18\x04 \x01(\x05R#uniqueContextIdentifierEnabledCount\x12R\n" +
	"$uniqueContextIdentifierDisabledCount\x18\x05 \x01(\x05R$uniqueContextIdentifierDisabledCount\x12<\n" +
	"\x19uniqueRequestEnabledCount\x18\x06 \x01(\x05R\x19uniqueRequestEnabledCount\x12>\n" +
	"\x1auniqueRequestDisabledCount\x18\a \x01(\x05R\x1auniqueRequestDisabledCount\x12\x1c\n" +
	"\tusedCount\x18\b \x01(\x05R\tusedCount\x122\n" +
	"\x14uniqueUsersUsedCount\x18\t \x01(\x05R\x14uniqueUsersUsedCount\x12.\n" +
	"\x10uniqueUserHashes\x18\n" +
	" \x03(\x05B\x02\x10\x01R\x10uniqueUserHashes\"0\n" +
	"\n" +
	"StatResult\x12\"\n" +
	"\ffeatureCount\x18\x01 \x01(\x05R\ffeatureCount2;\n" +
	"\x05Usage\x122\n" +
	"\tSendStats\x12\x12.Usage.FeatureStat\x1a\x11.Usage.StatResultBKZIgithub.com/ops-ai/Toggly.FeatureManagement/toggly-go/toggly/usage/usagepbb\x06proto3"

var (
	file_usage_proto_rawDescOnce sync.Once
	file_usage_proto_rawDescData []byte
)

func file_usage_proto_rawDescGZIP() []byte {
	file_usage_proto_rawDescOnce.Do(func() {
		file_usage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_usage_proto_rawDesc), len(file_usage_proto_rawDesc)))
	})
	return file_usage_proto_rawDescData
}

var file_usage_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_usage_proto_goTypes = []any{
	(*FeatureStat)(nil),           // 0: Usage.FeatureStat
	(*StatMessage)(nil),           // 1: Usage.StatMessage
	(*StatResult)(nil),            // 2: Usage.StatResult
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_usage_proto_depIdxs = []int32{
	3, // 0: Usage.FeatureStat.time:type_name -> google.protobuf.Timestamp
	1, // 1: Usage.FeatureStat.stats:type_name -> Usage.StatMessage
	3, // 2: Usage.FeatureStat.processStartTime:type_name -> google.protobuf.Timestamp
	0, // 3: Usage.Usage.SendStats:input_type -> Usage.FeatureStat
	2, // 4: Usage.Usage.SendStats:output_type -> Usage.StatResult
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_usage_proto_init() }
func file_usage_proto_init() {
	if File_usage_proto != nil {
		return
	}
	file_usage_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_usage_proto_rawDesc), len(file_usage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_usage_proto_goTypes,
		DependencyIndexes: file_usage_proto_depIdxs,
		MessageInfos:      file_usage_proto_msgTypes,
	}.Build()
	File_usage_proto = out.File
	file_usage_proto_goTypes = nil
	file_usage_proto_depIdxs = nil
}
