defmodule Toggly.VariantCorpusTest do
  @moduledoc """
  MF-parity gold corpus replay: `variant-allocator-corpus/cases.json`.

  Every case was generated by driving the real
  `Microsoft.FeatureManagement.FeatureManager.GetVariantAsync` (pinned to
  4.7.0); see `variant-allocator-corpus/README.md`. `Toggly.Variant.assign/3`
  must match every case bit-for-bit.
  """
  use ExUnit.Case, async: true

  @corpus_path Path.expand("../../../../variant-allocator-corpus/cases.json", __DIR__)
  @cases Jason.decode!(File.read!(@corpus_path))
  @expected_case_count 18

  test "corpus has the expected case count" do
    assert length(@cases) == @expected_case_count
  end

  for case_ <- @cases do
    @case_data case_

    test "gold corpus case #{case_["id"]}" do
      feature = @case_data["feature"]
      targeting = @case_data["targeting"]
      expected = @case_data["expected"]
      ignore_case = @case_data["ignoreCase"] || false

      definition = %{
        "featureKey" => feature["name"],
        "filters" => Enum.map(feature["enabledFor"] || [], &%{"name" => &1["name"]}),
        "variants" => feature["variants"] || [],
        "allocation" => feature["allocation"]
      }

      context = %{
        "identity" => targeting["userId"],
        "groups" => targeting["groups"] || []
      }

      assignment = Toggly.Variant.assign(definition, context, ignore_case: ignore_case)

      assert assignment.variant_name == expected["variantName"]
      assert assignment.configuration_value == expected["configurationValue"]
      assert assignment.enabled == expected["enabled"]
      assert assignment.assignment_reason == expected["assignmentReason"]
    end
  end
end
