# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- multitenant

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '86986db6-cabf-436b-a436-2cf8c1337c1b'
  imageRepository: 'togglydemo'
  containerRegistry: 'opsairegistry.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/examples/Demo.Mvc/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: CmdLine@2
      inputs:
        script: 'sed -e ''s/latest/$(tag)/g'' demo-prod.yaml > $(Build.ArtifactStagingDirectory)/demo-prod.yml'
        workingDirectory: '$(Build.SourcesDirectory)/charts/'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'charts'
        publishLocation: 'Container'
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'build'
        Dockerfile: 'examples/Demo.Mvc/Dockerfile'
        buildContext: 'examples'
        tags: '$(tag)'
        arguments: '--build-arg VERSION=$(tag)'
    - task: Docker@2
      displayName: Push an image to container registry
      inputs:
        containerRegistry: 'opsairegistry'
        repository: '$(imageRepository)'
        command: 'push'
