# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- develop

pool:
  vmImage: 'windows-2022'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1
  inputs:
    versionSpec: 
    checkLatest: true

- task: gitversion/setup@0
  inputs:
    versionSpec: '5.x'
    
- task: gitversion/execute@0
  inputs:
    updateAssemblyInfo: true
    updateAssemblyInfoFilename: '$(Build.SourcesDirectory)\Toggly.FeatureMangement.NET\AssemblyInfo.cs'
    additionalArguments: '/output buildserver'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'ops-ai'
    scannerMode: 'MSBuild'
    projectKey: 'ops-ai_toggly-feature-management'
    projectName: 'Toggly Feature Management'
    projectVersion: '0.1'
    extraProperties: |
      sonar.dependencyCheck.reportPath=$(Agent.BuildDirectory)\dependency-check-report.xml
      sonar.dependencyCheck.htmlReportPath=$(Agent.BuildDirectory)\dependency-check-report.html
      sonar.coverageReportPaths=$(Agent.TempDirectory)\SonarQube.xml
      sonar.coverage.exclusions="**Tests*.cs"

- task: dependency-check-build-task@5
  inputs:
    projectName: '$(Build.DefinitionName)'
    scanPath: '$(build.artifactstagingdirectory)'
    format: 'ALL'
    additionalArguments: '--disableBundleAudit --disableRubygems --disableNodeJS --disablePyPkg --disablePyDist --out "$(Agent.BuildDirectory)"'
  continueOnError: true

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '7.0.100'

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    configuration: $(buildConfiguration)

- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: test
    projects: '$(solution)'
    arguments: '-c $(buildConfiguration) --collect:"XPlat Code Coverage"'

- task: DotNetCoreCLI@2
  inputs:
    command: publish
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    projects: '$(solution)'
    publishWebProjects: true
    modifyOutputPath: true
    zipAfterPublish: true

- task: reportgenerator@4
  inputs:
    reports: '$(Agent.TempDirectory)\**\coverage.cobertura.xml'
    targetdir: '$(Agent.TempDirectory)\'
    reporttypes: 'SonarQube'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '$(solution)'
    versioningScheme: 'byBuildNumber'

- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
