import XCTest
@testable import TogglyCore

final class TogglyServiceTests: XCTestCase {
    func testInitWithDefaults() async {
        let defaults: FeatureFlags = ["feature1": true, "feature2": false]
        let config = TogglyConfig(featureDefaults: defaults)
        let service = TogglyService(config: config)

        let response = await service.initialize()

        XCTAssertEqual(response.status, .defaults)
        XCTAssertEqual(response.flags, defaults)
    }

    func testIsFeatureOnWithDefaults() async {
        let defaults: FeatureFlags = ["feature1": true, "feature2": false]
        let config = TogglyConfig(featureDefaults: defaults)
        let service = TogglyService(config: config)

        await service.initialize()

        let feature1 = await service.isFeatureOn("feature1")
        let feature2 = await service.isFeatureOn("feature2")
        let feature3 = await service.isFeatureOn("feature3")

        XCTAssertTrue(feature1)
        XCTAssertFalse(feature2)
        XCTAssertFalse(feature3) // Non-existent defaults to false
    }

    func testIsFeatureOffWithDefaults() async {
        let defaults: FeatureFlags = ["feature1": true, "feature2": false]
        let config = TogglyConfig(featureDefaults: defaults)
        let service = TogglyService(config: config)

        await service.initialize()

        let feature1 = await service.isFeatureOff("feature1")
        let feature2 = await service.isFeatureOff("feature2")

        XCTAssertFalse(feature1)
        XCTAssertTrue(feature2)
    }

    func testEvaluateFeatureGateAll() async {
        let defaults: FeatureFlags = ["f1": true, "f2": true, "f3": false]
        let config = TogglyConfig(featureDefaults: defaults)
        let service = TogglyService(config: config)

        await service.initialize()

        let allEnabled = await service.evaluateFeatureGate(
            featureKeys: ["f1", "f2"],
            requirement: .all
        )
        let notAllEnabled = await service.evaluateFeatureGate(
            featureKeys: ["f1", "f3"],
            requirement: .all
        )

        XCTAssertTrue(allEnabled)
        XCTAssertFalse(notAllEnabled)
    }

    func testEvaluateFeatureGateAny() async {
        let defaults: FeatureFlags = ["f1": true, "f2": false, "f3": false]
        let config = TogglyConfig(featureDefaults: defaults)
        let service = TogglyService(config: config)

        await service.initialize()

        let anyEnabled = await service.evaluateFeatureGate(
            featureKeys: ["f1", "f2"],
            requirement: .any
        )
        let noneEnabled = await service.evaluateFeatureGate(
            featureKeys: ["f2", "f3"],
            requirement: .any
        )

        XCTAssertTrue(anyEnabled)
        XCTAssertFalse(noneEnabled)
    }

    func testEvaluateFeatureGateNegate() async {
        let defaults: FeatureFlags = ["feature1": true]
        let config = TogglyConfig(featureDefaults: defaults)
        let service = TogglyService(config: config)

        await service.initialize()

        let normal = await service.evaluateFeatureGate(
            featureKeys: ["feature1"],
            requirement: .all,
            negate: false
        )
        let negated = await service.evaluateFeatureGate(
            featureKeys: ["feature1"],
            requirement: .all,
            negate: true
        )

        XCTAssertTrue(normal)
        XCTAssertFalse(negated)
    }

    func testEvaluateEmptyFeatureGate() async {
        let config = TogglyConfig()
        let service = TogglyService(config: config)

        await service.initialize()

        let result = await service.evaluateFeatureGate(featureKeys: [])

        XCTAssertTrue(result) // Empty gate defaults to true
    }

    func testIdentityFromConfig() async {
        let config = TogglyConfig(identity: "user-123")
        let service = TogglyService(config: config)

        await service.initialize()

        let identity = await service.currentIdentity
        XCTAssertEqual(identity, "user-123")
    }

    func testSetIdentity() async {
        let config = TogglyConfig(identity: "user-1")
        let service = TogglyService(config: config)

        await service.initialize()
        await service.setIdentity("user-2")

        let identity = await service.currentIdentity
        XCTAssertEqual(identity, "user-2")
    }

    func testAutoGeneratedIdentity() async {
        let config = TogglyConfig()
        let service = TogglyService(config: config)

        await service.initialize()

        let identity = await service.currentIdentity
        XCTAssertNotNil(identity)
        XCTAssertFalse(identity!.isEmpty)
    }

    func testDebugInfo() async {
        let config = TogglyConfig(
            appKey: "test-key",
            environment: "Test",
            identity: "user-123"
        )
        let service = TogglyService(config: config)

        await service.initialize()

        let debugInfo = await service.getDebugInfo()

        XCTAssertEqual(debugInfo.identity, "user-123")
        XCTAssertEqual(debugInfo.appKey, "test-key")
        XCTAssertEqual(debugInfo.environment, "Test")
        XCTAssertEqual(debugInfo.appState, .active)
    }

    func testAppStateChange() async {
        let config = TogglyConfig()
        let service = TogglyService(config: config)

        await service.initialize()
        await service.setAppState(.background)

        let debugInfo = await service.getDebugInfo()
        XCTAssertEqual(debugInfo.appState, .background)
        XCTAssertFalse(debugInfo.isAppInForeground)
    }

    func testNetworkStateChange() async {
        let config = TogglyConfig()
        let service = TogglyService(config: config)

        await service.initialize()
        await service.setNetworkState(.disconnected)

        let debugInfo = await service.getDebugInfo()
        XCTAssertEqual(debugInfo.networkState, .disconnected)
    }

    func testEventSubscription() async {
        let config = TogglyConfig()
        let service = TogglyService(config: config)

        var receivedEvents: [TogglyEvent] = []
        let expectation = XCTestExpectation(description: "Receive initialized event")

        _ = await service.on { event in
            receivedEvents.append(event)
            if case .initialized = event {
                expectation.fulfill()
            }
        }

        await service.initialize()

        await fulfillment(of: [expectation], timeout: 1.0)
        XCTAssertFalse(receivedEvents.isEmpty)
    }

    func testStateChangeHandler() async {
        let defaults: FeatureFlags = ["feature1": true]
        let config = TogglyConfig(featureDefaults: defaults)
        let service = TogglyService(config: config)

        var changedFeatures: [(String, Bool?, Bool?)] = []

        _ = await service.addStateChangeHandler { key, previousValue, newValue in
            changedFeatures.append((key, previousValue, newValue))
        }

        await service.initialize()

        // Note: In a real scenario, changes would be triggered by server updates
        // This test verifies the handler is registered correctly
        XCTAssertTrue(changedFeatures.isEmpty) // No changes yet
    }

    func testDispose() async {
        let config = TogglyConfig(refreshInterval: 1)
        let service = TogglyService(config: config)

        await service.initialize()
        let initializedBefore = await service.initialized
        XCTAssertTrue(initializedBefore)

        await service.dispose()

        let initializedAfter = await service.initialized
        XCTAssertFalse(initializedAfter)
    }

    func testClearCache() async {
        let defaults: FeatureFlags = ["feature1": true]
        let config = TogglyConfig(featureDefaults: defaults)
        let service = TogglyService(config: config)

        await service.initialize()
        await service.clearCache()

        // After clearing cache, should still work with defaults
        let isOn = await service.isFeatureOn("feature1")
        XCTAssertTrue(isOn)
    }
}
