name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies (core)
        working-directory: remix-toggly-core
        run: npm ci

      - name: Build (core)
        working-directory: remix-toggly-core
        run: npm run build

      - name: Test (core)
        working-directory: remix-toggly-core
        run: npm run test:coverage

      - name: Publish (core)
        working-directory: remix-toggly-core
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install dependencies (server)
        working-directory: remix-toggly-server
        run: npm ci

      - name: Build (server)
        working-directory: remix-toggly-server
        run: npm run build

      - name: Test (server)
        working-directory: remix-toggly-server
        run: npm run test:coverage

      - name: Publish (server)
        working-directory: remix-toggly-server
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install dependencies (client)
        working-directory: remix-toggly-client
        run: npm ci

      - name: Build (client)
        working-directory: remix-toggly-client
        run: npm run build

      - name: Test (client)
        working-directory: remix-toggly-client
        run: npm run test:coverage

      - name: Publish (client)
        working-directory: remix-toggly-client
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
