name: feature_flags_toggly_disk_example
description: Example for feature_flags_toggly_disk.
publish_to: 'none'

environment:
  sdk: '>=2.18.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  feature_flags_toggly_disk:
    path: ../

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
