"""Replay the shared MF variant-allocator gold corpus against `assign_variant`.

Every Toggly backend SDK implementing catalog-local feature variants must
pass 100% of `variant-allocator-corpus/cases.json` — the ground truth is
generated by a .NET harness that drives the real
`Microsoft.FeatureManagement.FeatureManager.GetVariantAsync` (pinned to
`Microsoft.FeatureManagement` 4.7.0). See
`variant-allocator-corpus/README.md` for the schema and regeneration steps.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest

from toggly.evaluator import EvaluationEngine
from toggly.models import Allocation, FeatureDefinition, FeatureFilter, Variant
from toggly.variants import assign_variant

_CORPUS_PATH = (
    Path(__file__).resolve().parents[3] / "variant-allocator-corpus" / "cases.json"
)


def _load_corpus() -> list[dict[str, Any]]:
    with open(_CORPUS_PATH, encoding="utf-8") as f:
        return json.load(f)


def _feature_definition(feature: dict[str, Any]) -> FeatureDefinition:
    """Build a FeatureDefinition from the corpus' MF-shaped fixture."""
    filters = [
        FeatureFilter(name=f["name"], parameters=f.get("parameters") or {})
        for f in feature.get("enabledFor") or []
    ]
    variants = [
        v
        for v in (Variant.from_dict(x) for x in feature.get("variants") or [])
        if v is not None
    ]
    allocation = Allocation.from_dict(feature.get("allocation"))
    return FeatureDefinition(
        feature_key=feature["name"],
        filters=filters,
        variants=variants,
        allocation=allocation,
    )


_CORPUS = _load_corpus()
assert _CORPUS, "corpus must not be empty"


@pytest.mark.parametrize("case", _CORPUS, ids=[c["id"] for c in _CORPUS])
def test_corpus_case(case: dict[str, Any]) -> None:
    """Each corpus case's expected variant/config/enabled/reason must match exactly."""
    definition = _feature_definition(case["feature"])
    targeting = case["targeting"]
    expected = case["expected"]
    ignore_case = bool(case.get("ignoreCase", False))

    # The corpus' `enabledFor` list drives MF's own filter evaluation (identical
    # semantics to our AlwaysOn/AlwaysOff evaluators for these fixtures).
    engine = EvaluationEngine()
    from toggly.context import EvaluationContext

    context = EvaluationContext(
        identity=targeting.get("userId"), groups=targeting.get("groups") or []
    )
    enabled = engine.evaluate(definition, context)

    assignment = assign_variant(
        definition,
        enabled=enabled,
        user_id=targeting.get("userId"),
        groups=targeting.get("groups") or [],
        ignore_case=ignore_case,
    )

    assert assignment.reason == expected["assignmentReason"]
    assert assignment.enabled == expected["enabled"]
    if expected["variantName"] is None:
        assert assignment.variant is None
    else:
        assert assignment.variant is not None
        assert assignment.variant.name == expected["variantName"]
        assert assignment.variant.configuration_value == expected["configurationValue"]
