# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Android
android.useAndroidX=true
android.nonTransitiveRClass=true

# Kotlin
kotlin.code.style=official
kotlin.incremental=true

# Maven Publishing
POM_NAME=Toggly Android SDK
POM_DESCRIPTION=Feature flags SDK for Android applications
POM_URL=https://github.com/ops-ai/Toggly.FeatureManagement
POM_SCM_URL=https://github.com/ops-ai/Toggly.FeatureManagement
POM_SCM_CONNECTION=scm:git:git://github.com/ops-ai/Toggly.FeatureManagement.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://github.com/ops-ai/Toggly.FeatureManagement.git
POM_LICENCE_NAME=MIT License
POM_LICENCE_URL=https://opensource.org/licenses/MIT
POM_DEVELOPER_ID=toggly
POM_DEVELOPER_NAME=Toggly
POM_DEVELOPER_EMAIL=hello@toggly.io
