# frozen_string_literal: true

source "https://rubygems.org"

gemspec

gem "toggly", path: "../toggly"

group :development, :test do
  gem "mock_redis", "~> 0.44"
  gem "parallel", "~> 1.27"
  gem "rake", "~> 13.0"
  gem "rspec", "~> 3.12"
  gem "rubocop", "~> 1.90", require: false
  gem "rubocop-rspec", "~> 3.10", require: false
  gem "simplecov", "~> 0.22", require: false
  gem "webmock", "~> 3.26"
end
