# frozen_string_literal: true

source "https://rubygems.org"

gemspec

group :development, :test do
  gem "rspec", "~> 3.12"
  gem "webmock", "~> 3.18"
  gem "simplecov", "~> 0.22", require: false
  gem "rubocop", "~> 1.56", require: false
  gem "rubocop-rspec", "~> 2.24", require: false
  gem "yard", "~> 0.9", require: false
  gem "rake", "~> 13.0"
  gem "websocket-client-simple", "~> 0.8"
end
