name: sync_repository
description: Dart package which manages the timers.
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  equatable: ^2.0.0
  uuid: ^3.0.0
  http: ^0.13.4 
  secure_storage_repository:
    path: ../secure_storage_repository