syntax = "proto3";

package Metrics;

option go_package = "github.com/ops-ai/Toggly.FeatureManagement/toggly-go/toggly/metrics/metricspb";

import "google/protobuf/timestamp.proto";

message MetricStat {
  string appKey = 1;
  string environment = 2;
  google.protobuf.Timestamp time = 3;
  repeated MetricStatMessage stats = 4;
  repeated MetricCounterMessage counters = 5;
  repeated MetricObservationMessage observations = 6;
  optional string instanceName = 7;
}

message MetricStatMessage {
  string metric = 1;
  optional string feature = 4;
  double value = 5;
  optional double valueDisabled = 6;
}

message MetricCounterMessage {
  string metric = 1;
  optional string feature = 4;
  double value = 5;
  optional double valueDisabled = 6;
}

message MetricObservationMessage {
  google.protobuf.Timestamp time = 1;
  string metric = 2;
  optional string feature = 5;
  double value = 6;
  optional double valueDisabled = 7;
}

message MetricResult {
  int32 count = 1;
}

service Metrics {
  rpc SendMetrics(MetricStat) returns (MetricResult);
}
