name: http_service
description: Dart package which handles the http requests (uses Dio).
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  dio: ^4.0.5-beta1
  equatable: ^2.0.0
  uuid: ^3.0.0
  http: ^0.13.4 
  secure_storage_repository:
    path: ../secure_storage_repository
  dio_smart_retry: ^1.2.0