AllCops:
  NewCops: enable
  SuggestExtensions: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Naming/FileName:
  Exclude:
    - '**/lib/toggly-rails.rb'
