name: feature_flags_toggly_disk
description: On-disk (plain JSON file) persistence backend for the Toggly Flutter SDK (feature_flags_toggly), enabling offline feature flag, variant, and JWKS caching.
version: 0.3.0
homepage: https://docs.toggly.io/
repository: https://github.com/ops-ai/Toggly.FeatureManagement

environment:
  sdk: '>=2.18.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  feature_flags_toggly: '>=1.8.0 <2.0.0'
  path: '>=1.8.0 <2.0.0'
  path_provider: '>=2.0.0 <3.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  lints: ^2.0.1

flutter:
