<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.1;netcoreapp3.1;net5.0;net6.0;net7.0;net8.0;net9.0;net10.0</TargetFrameworks>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageId>Toggly.FeatureManagement.Storage.MongoDB</PackageId>
    <Description>MongoDB snapshot provider for Toggly Feature Management. Store feature flag snapshots in MongoDB for high availability and scalability.</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>toggly;feature-flags;feature-management;mongodb;nosql;snapshot provider</PackageTags>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <AssemblyTitle>Toggly MongoDB Feature Snapshot Provider</AssemblyTitle>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'netstandard2.1'">
    <LangVersion>9.0</LangVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'netcoreapp3.1'">
    <LangVersion>9.0</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\AssemblyInfo.cs" Link="Properties\AssemblyInfo.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md">
      <PackagePath>\</PackagePath>
      <Pack>True</Pack>
    </None>
  </ItemGroup>

<ItemGroup>
    <PackageReference Include="MongoDB.Driver" Version="2.29.0" />

  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Toggly.FeatureManagement\Toggly.FeatureManagement.csproj" />
  </ItemGroup>

</Project>
