sonar.projectKey=toggly-sdks-dotnet
sonar.organization=ops-ai
sonar.sources=src
sonar.tests=tests
sonar.exclusions=**/bin/**,**/obj/**
sonar.cs.opencover.reportsPaths=tests/**/TestResults/**/coverage.opencover.xml
