# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import usage_pb2 as usage__pb2

GRPC_GENERATED_VERSION = '1.62.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in usage_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UsageStub(object):
    """Feature usage statistics service (field numbers match .NET Usage.proto).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendStats = channel.unary_unary(
                '/Usage.Usage/SendStats',
                request_serializer=usage__pb2.FeatureStat.SerializeToString,
                response_deserializer=usage__pb2.StatResult.FromString,
                _registered_method=True)


class UsageServicer(object):
    """Feature usage statistics service (field numbers match .NET Usage.proto).
    """

    def SendStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UsageServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendStats': grpc.unary_unary_rpc_method_handler(
                    servicer.SendStats,
                    request_deserializer=usage__pb2.FeatureStat.FromString,
                    response_serializer=usage__pb2.StatResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Usage.Usage', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Usage.Usage', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Usage(object):
    """Feature usage statistics service (field numbers match .NET Usage.proto).
    """

    @staticmethod
    def SendStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Usage.Usage/SendStats',
            usage__pb2.FeatureStat.SerializeToString,
            usage__pb2.StatResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
