# frozen_string_literal: true

source "https://rubygems.org"

gemspec

gem "toggly", path: "../toggly"

group :development, :test do
  gem "parallel", "~> 1.27"
  # Ruby 4 no longer ships OpenStruct as a default gem; the Rails specs use it
  # to construct request users and controller fixtures.
  gem "ostruct", "~> 0.6"
  gem "rails", ENV.fetch("RAILS_VERSION", ">= 7.0")
  gem "rake", "~> 13.0"
  gem "rspec", "~> 3.12"
  gem "rspec-rails", "~> 6.0"
  gem "rubocop", "~> 1.91", require: false
  gem "rubocop-rspec", "~> 2.24", require: false
  gem "simplecov", "~> 1.2", require: false
  gem "sqlite3", "~> 2.9"
  gem "webmock", "~> 3.26"
end
