# frozen_string_literal: true
# Generated by the protocol buffer compiler. DO NOT EDIT!
# Source: metrics.proto for package 'Metrics'

require "grpc"
require_relative "metrics_pb"

module Toggly
  module Telemetry
    module Pb
      module Metrics
        module Metrics
          class Service
            include ::GRPC::GenericService

            self.marshal_class_method = :encode
            self.unmarshal_class_method = :decode
            self.service_name = "Metrics.Metrics"

            rpc :SendMetrics, ::Toggly::Telemetry::Pb::Metrics::MetricStat, ::Toggly::Telemetry::Pb::Metrics::MetricResult
          end

          Stub = Service.rpc_stub_class
        end
      end
    end
  end
end
