# frozen_string_literal: true
# Generated by the protocol buffer compiler. DO NOT EDIT!
# Source: usage.proto for package 'Usage'

require "grpc"
require_relative "usage_pb"

module Toggly
  module Telemetry
    module Pb
      module Usage
        module Usage
          class Service
            include ::GRPC::GenericService

            self.marshal_class_method = :encode
            self.unmarshal_class_method = :decode
            self.service_name = "Usage.Usage"

            rpc :SendStats, ::Toggly::Telemetry::Pb::Usage::FeatureStat, ::Toggly::Telemetry::Pb::Usage::StatResult
          end

          Stub = Service.rpc_stub_class
        end
      end
    end
  end
end
