<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net6.0;net8.0;net9.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageId>Toggly.FeatureManagement.Storage.Dapper</PackageId>
    <Description>Dapper snapshot provider for Toggly Feature Management. Lightweight and fast SQL-based storage for feature flag snapshots supporting SQL Server, PostgreSQL, MySQL, and SQLite.</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>toggly;feature-flags;feature-management;dapper;sql;snapshot provider</PackageTags>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <AssemblyTitle>Toggly Dapper Feature Snapshot Provider</AssemblyTitle>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\AssemblyInfo.cs" Link="Properties\AssemblyInfo.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md">
      <PackagePath>\</PackagePath>
      <Pack>True</Pack>
    </None>
  </ItemGroup>

<ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.35" />

  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Toggly.FeatureManagement\Toggly.FeatureManagement.csproj" />
  </ItemGroup>

</Project>
