// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: metrics.proto

package metricspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetricStat struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	AppKey        string                      `protobuf:"bytes,1,opt,name=appKey,proto3" json:"appKey,omitempty"`
	Environment   string                      `protobuf:"bytes,2,opt,name=environment,proto3" json:"environment,omitempty"`
	Time          *timestamppb.Timestamp      `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
	Stats         []*MetricStatMessage        `protobuf:"bytes,4,rep,name=stats,proto3" json:"stats,omitempty"`
	Counters      []*MetricCounterMessage     `protobuf:"bytes,5,rep,name=counters,proto3" json:"counters,omitempty"`
	Observations  []*MetricObservationMessage `protobuf:"bytes,6,rep,name=observations,proto3" json:"observations,omitempty"`
	InstanceName  *string                     `protobuf:"bytes,7,opt,name=instanceName,proto3,oneof" json:"instanceName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricStat) Reset() {
	*x = MetricStat{}
	mi := &file_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricStat) ProtoMessage() {}

func (x *MetricStat) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricStat.ProtoReflect.Descriptor instead.
func (*MetricStat) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *MetricStat) GetAppKey() string {
	if x != nil {
		return x.AppKey
	}
	return ""
}

func (x *MetricStat) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *MetricStat) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *MetricStat) GetStats() []*MetricStatMessage {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *MetricStat) GetCounters() []*MetricCounterMessage {
	if x != nil {
		return x.Counters
	}
	return nil
}

func (x *MetricStat) GetObservations() []*MetricObservationMessage {
	if x != nil {
		return x.Observations
	}
	return nil
}

func (x *MetricStat) GetInstanceName() string {
	if x != nil && x.InstanceName != nil {
		return *x.InstanceName
	}
	return ""
}

type MetricStatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        string                 `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	Feature       *string                `protobuf:"bytes,4,opt,name=feature,proto3,oneof" json:"feature,omitempty"`
	Value         float64                `protobuf:"fixed64,5,opt,name=value,proto3" json:"value,omitempty"`
	ValueDisabled *float64               `protobuf:"fixed64,6,opt,name=valueDisabled,proto3,oneof" json:"valueDisabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricStatMessage) Reset() {
	*x = MetricStatMessage{}
	mi := &file_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricStatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricStatMessage) ProtoMessage() {}

func (x *MetricStatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricStatMessage.ProtoReflect.Descriptor instead.
func (*MetricStatMessage) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{1}
}

func (x *MetricStatMessage) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *MetricStatMessage) GetFeature() string {
	if x != nil && x.Feature != nil {
		return *x.Feature
	}
	return ""
}

func (x *MetricStatMessage) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *MetricStatMessage) GetValueDisabled() float64 {
	if x != nil && x.ValueDisabled != nil {
		return *x.ValueDisabled
	}
	return 0
}

type MetricCounterMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        string                 `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	Feature       *string                `protobuf:"bytes,4,opt,name=feature,proto3,oneof" json:"feature,omitempty"`
	Value         float64                `protobuf:"fixed64,5,opt,name=value,proto3" json:"value,omitempty"`
	ValueDisabled *float64               `protobuf:"fixed64,6,opt,name=valueDisabled,proto3,oneof" json:"valueDisabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricCounterMessage) Reset() {
	*x = MetricCounterMessage{}
	mi := &file_metrics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricCounterMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricCounterMessage) ProtoMessage() {}

func (x *MetricCounterMessage) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricCounterMessage.ProtoReflect.Descriptor instead.
func (*MetricCounterMessage) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{2}
}

func (x *MetricCounterMessage) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *MetricCounterMessage) GetFeature() string {
	if x != nil && x.Feature != nil {
		return *x.Feature
	}
	return ""
}

func (x *MetricCounterMessage) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *MetricCounterMessage) GetValueDisabled() float64 {
	if x != nil && x.ValueDisabled != nil {
		return *x.ValueDisabled
	}
	return 0
}

type MetricObservationMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Metric        string                 `protobuf:"bytes,2,opt,name=metric,proto3" json:"metric,omitempty"`
	Feature       *string                `protobuf:"bytes,5,opt,name=feature,proto3,oneof" json:"feature,omitempty"`
	Value         float64                `protobuf:"fixed64,6,opt,name=value,proto3" json:"value,omitempty"`
	ValueDisabled *float64               `protobuf:"fixed64,7,opt,name=valueDisabled,proto3,oneof" json:"valueDisabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricObservationMessage) Reset() {
	*x = MetricObservationMessage{}
	mi := &file_metrics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricObservationMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricObservationMessage) ProtoMessage() {}

func (x *MetricObservationMessage) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricObservationMessage.ProtoReflect.Descriptor instead.
func (*MetricObservationMessage) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{3}
}

func (x *MetricObservationMessage) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *MetricObservationMessage) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *MetricObservationMessage) GetFeature() string {
	if x != nil && x.Feature != nil {
		return *x.Feature
	}
	return ""
}

func (x *MetricObservationMessage) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *MetricObservationMessage) GetValueDisabled() float64 {
	if x != nil && x.ValueDisabled != nil {
		return *x.ValueDisabled
	}
	return 0
}

type MetricResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricResult) Reset() {
	*x = MetricResult{}
	mi := &file_metrics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricResult) ProtoMessage() {}

func (x *MetricResult) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricResult.ProtoReflect.Descriptor instead.
func (*MetricResult) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{4}
}

func (x *MetricResult) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_metrics_proto protoreflect.FileDescriptor

const file_metrics_proto_rawDesc = "" +
	"\n" +
	"\rmetrics.proto\x12\aMetrics\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe4\x02\n" +
	"\n" +
	"MetricStat\x12\x16\n" +
	"\x06appKey\x18\x01 \x01(\tR\x06appKey\x12 \n" +
	"\venvironment\x18\x02 \x01(\tR\venvironment\x12.\n" +
	"\x04time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x120\n" +
	"\x05stats\x18\x04 \x03(\v2\x1a.Metrics.MetricStatMessageR\x05stats\x129\n" +
	"\bcounters\x18\x05 \x03(\v2\x1d.Metrics.MetricCounterMessageR\bcounters\x12E\n" +
	"\fobservations\x18\x06 \x03(\v2!.Metrics.MetricObservationMessageR\fobservations\x12'\n" +
	"\finstanceName\x18\a \x01(\tH\x00R\finstanceName\x88\x01\x01B\x0f\n" +
	"\r_instanceName\"\xa9\x01\n" +
	"\x11MetricStatMessage\x12\x16\n" +
	"\x06metric\x18\x01 \x01(\tR\x06metric\x12\x1d\n" +
	"\afeature\x18\x04 \x01(\tH\x00R\afeature\x88\x01\x01\x12\x14\n" +
	"\x05value\x18\x05 \x01(\x01R\x05value\x12)\n" +
	"\rvalueDisabled\x18\x06 \x01(\x01H\x01R\rvalueDisabled\x88\x01\x01B\n" +
	"\n" +
	"\b_featureB\x10\n" +
	"\x0e_valueDisabled\"\xac\x01\n" +
	"\x14MetricCounterMessage\x12\x16\n" +
	"\x06metric\x18\x01 \x01(\tR\x06metric\x12\x1d\n" +
	"\afeature\x18\x04 \x01(\tH\x00R\afeature\x88\x01\x01\x12\x14\n" +
	"\x05value\x18\x05 \x01(\x01R\x05value\x12)\n" +
	"\rvalueDisabled\x18\x06 \x01(\x01H\x01R\rvalueDisabled\x88\x01\x01B\n" +
	"\n" +
	"\b_featureB\x10\n" +
	"\x0e_valueDisabled\"\xe0\x01\n" +
	"\x18MetricObservationMessage\x12.\n" +
	"\x04time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x16\n" +
	"\x06metric\x18\x02 \x01(\tR\x06metric\x12\x1d\n" +
	"\afeature\x18\x05 \x01(\tH\x00R\afeature\x88\x01\x01\x12\x14\n" +
	"\x05value\x18\x06 \x01(\x01R\x05value\x12)\n" +
	"\rvalueDisabled\x18\a \x01(\x01H\x01R\rvalueDisabled\x88\x01\x01B\n" +
	"\n" +
	"\b_featureB\x10\n" +
	"\x0e_valueDisabled\"$\n" +
	"\fMetricResult\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count2D\n" +
	"\aMetrics\x129\n" +
	"\vSendMetrics\x12\x13.Metrics.MetricStat\x1a\x15.Metrics.MetricResultBOZMgithub.com/ops-ai/Toggly.FeatureManagement/toggly-go/toggly/metrics/metricspbb\x06proto3"

var (
	file_metrics_proto_rawDescOnce sync.Once
	file_metrics_proto_rawDescData []byte
)

func file_metrics_proto_rawDescGZIP() []byte {
	file_metrics_proto_rawDescOnce.Do(func() {
		file_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metrics_proto_rawDesc), len(file_metrics_proto_rawDesc)))
	})
	return file_metrics_proto_rawDescData
}

var file_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_metrics_proto_goTypes = []any{
	(*MetricStat)(nil),               // 0: Metrics.MetricStat
	(*MetricStatMessage)(nil),        // 1: Metrics.MetricStatMessage
	(*MetricCounterMessage)(nil),     // 2: Metrics.MetricCounterMessage
	(*MetricObservationMessage)(nil), // 3: Metrics.MetricObservationMessage
	(*MetricResult)(nil),             // 4: Metrics.MetricResult
	(*timestamppb.Timestamp)(nil),    // 5: google.protobuf.Timestamp
}
var file_metrics_proto_depIdxs = []int32{
	5, // 0: Metrics.MetricStat.time:type_name -> google.protobuf.Timestamp
	1, // 1: Metrics.MetricStat.stats:type_name -> Metrics.MetricStatMessage
	2, // 2: Metrics.MetricStat.counters:type_name -> Metrics.MetricCounterMessage
	3, // 3: Metrics.MetricStat.observations:type_name -> Metrics.MetricObservationMessage
	5, // 4: Metrics.MetricObservationMessage.time:type_name -> google.protobuf.Timestamp
	0, // 5: Metrics.Metrics.SendMetrics:input_type -> Metrics.MetricStat
	4, // 6: Metrics.Metrics.SendMetrics:output_type -> Metrics.MetricResult
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_metrics_proto_init() }
func file_metrics_proto_init() {
	if File_metrics_proto != nil {
		return
	}
	file_metrics_proto_msgTypes[0].OneofWrappers = []any{}
	file_metrics_proto_msgTypes[1].OneofWrappers = []any{}
	file_metrics_proto_msgTypes[2].OneofWrappers = []any{}
	file_metrics_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metrics_proto_rawDesc), len(file_metrics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_metrics_proto_goTypes,
		DependencyIndexes: file_metrics_proto_depIdxs,
		MessageInfos:      file_metrics_proto_msgTypes,
	}.Build()
	File_metrics_proto = out.File
	file_metrics_proto_goTypes = nil
	file_metrics_proto_depIdxs = nil
}
